# Config for https://github.com/apps/release-drafter
categories:
  - title: '🚀 Features'
    label: 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

replacers:
  - search: 'Update config drafter'
    replace: 'Prevention'
branches:
  - master
template: |
  ## What's Changed

  $CHANGES
  $CONTRIBUTORS
